### ISSUE TITLE
OM Lx ISO's will not boot w/EFI enabled. (Bugzilla Bug 2657)

### ISSUE THREAD

**Issue by tpgxyz** [OpenMandrivaAssociation/test2#2657]
This issue was created automatically with bugzilla2github
# Bugzilla Bug 2657
Date: 2020-11-18 14:36:25 +0000
From: @benbullard79
To:   @berolinux
CC:   @benbullard79, bugs@openmandriva.org, nix.or.die@gmail.com, nobodydead@gmail.com, @tpgxyz

Last updated: 2020-11-29 02:28:06 +0000

## Comment 20443
Date: 2020-11-18 14:36:25 +0000
From: @benbullard79

Created attachment 1930
VBox.log from failed attempt to boot ISO 3590 with EFI enabled.

Problem is this : Cooker w/virtualbox-6.1.16 no OM Lx ISO's will boot with EFI enabled.

Some information: Existing installed systems still boot with no problem.

Also in Rolling w/virtualbox-6.1.12 the same ISO's will EFI boot.

tpg has identified 2 upstream bug reports that cover this issue:

https://www.virtualbox.org/ticket/19682

https://www.virtualbox.org/ticket/19910

So developers are aware of and working on getting this RESOLVED.

There is an attached VBox.log of a failed attempt to boot in VBox  latest Cooker ISO # 3590 with EFI enabled.

To Reproduce: Install Cooker  and then install VirtualBox-6.1.16. Now set up as you normally do a new VM to use any OM Lx ISO and be sure it is set to use EFI. Now boot that. What we are seeing is that it will boot to interactive shell 100% or time. Also usual methods that should boot from that interactive shell do not work. Will not boot at all.

> Attached file: VBox.log (text/x-log, 187969 bytes)
> Description:   VBox.log from failed attempt to boot ISO 3590 with EFI enabled.

## Comment 20444
Date: 2020-11-18 14:38:09 +0000
From: @benbullard79

Marking this report VERIFIED/UPSTREAM. This bug is well established.

## Comment 20449
Date: 2020-11-19 04:39:44 +0000
From: Gabriel Craciunescu &lt;<nix.or.die@gmail.com>&gt;

I fixed this bug in Frugalware but is not yet ported over to OM.

Working with bero to get it done for OM too.

There a picture of OM plasma iso, EFI boot, running in vbox 6.1.16.

https://crazy.dev.frugalware.org/OM_vbox_efi_6.1.16.png

## Comment 20477
Date: 2020-11-29 02:28:06 +0000
From: @benbullard79

This is fixed.

**Comment by omakuta** [comment]
This issue has been mentioned on **OMA forum**. There might be relevant details there:

https://forum.openmandriva.org/t/new-rock-omlx-4-3-snapshot-isos-fixes-bug-2657/4447/1
